In [8]:
pip install dash

Requirement already satisfied: dash in c:\users\user\anaconda3\lib\site-packages (4.0.0)
Requirement already satisfied: Flask<3.2,>=1.0.4 in c:\users\user\anaconda3\lib\site-packages (from dash) (3.1.2)
Requirement already satisfied: Werkzeug<3.2 in c:\users\user\anaconda3\lib\site-packages (from dash) (3.1.3)
Requirement already satisfied: plotly>=5.0.0 in c:\users\user\anaconda3\lib\site-packages (from dash) (6.3.0)
Requirement already satisfied: importlib-metadata in c:\users\user\anaconda3\lib\site-packages (from dash) (8.7.0)
Requirement already satisfied: typing_extensions>=4.1.1 in c:\users\user\anaconda3\lib\site-packages (from dash) (4.15.0)
Requirement already satisfied: requests in c:\users\user\anaconda3\lib\site-packages (from dash) (2.32.5)
Requirement already satisfied: retrying in c:\users\user\anaconda3\lib\site-packages (from dash) (1.4.2)
Requirement already satisfied: nest-asyncio in c:\users\user\anaconda3\lib\site-packages (from dash) (1.6.0)
Requirement already satisfied: setuptools in c:\users\user\anaconda3\lib\site-packages (from dash) (80.9.0)
Requirement already satisfied: blinker>=1.9.0 in c:\users\user\anaconda3\lib\site-packages (from Flask<3.2,>=1.0.4->dash) (1.9.0)
Requirement already satisfied: click>=8.1.3 in c:\users\user\anaconda3\lib\site-packages (from Flask<3.2,>=1.0.4->dash) (8.2.1)
Requirement already satisfied: itsdangerous>=2.2.0 in c:\users\user\anaconda3\lib\site-packages (from Flask<3.2,>=1.0.4->dash) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in c:\users\user\anaconda3\lib\site-packages (from Flask<3.2,>=1.0.4->dash) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in c:\users\user\anaconda3\lib\site-packages (from Flask<3.2,>=1.0.4->dash) (3.0.2)
Requirement already satisfied: colorama in c:\users\user\anaconda3\lib\site-packages (from click>=8.1.3->Flask<3.2,>=1.0.4->dash) (0.4.6)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\user\anaconda3\lib\site-packages (from plotly>=5.0.0->dash) (2.7.0)
Requirement already satisfied: packaging in c:\users\user\anaconda3\lib\site-packages (from plotly>=5.0.0->dash) (25.0)
Requirement already satisfied: zipp>=3.20 in c:\users\user\anaconda3\lib\site-packages (from importlib-metadata->dash) (3.23.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\user\anaconda3\lib\site-packages (from requests->dash) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user\anaconda3\lib\site-packages (from requests->dash) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\user\anaconda3\lib\site-packages (from requests->dash) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\anaconda3\lib\site-packages (from requests->dash) (2026.1.4)
Note: you may need to restart the kernel to use updated packages.

In [9]:
pip install pandas

Requirement already satisfied: pandas in c:\users\user\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\user\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [10]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import dash
from dash import dash_table, html

In [6]:
df= pd.read_csv("C:/Users/User/Downloads/employee_data.csv")
df

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech      NaN  12-11-2020

In [11]:
df

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech      NaN  12-11-2020

In [14]:
df= df.fillna("Arun")
df

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech     Arun  12-11-2020
2  Mathiew  Arun    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6     Arun  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech     Arun  12-11-2020

In [15]:
df["Age"]=df["Age"].replace("Arun","28.0")
df

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech     Arun  12-11-2020
2  Mathiew  28.0    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6     Arun  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech     Arun  12-11-2020

In [16]:
df["Salary"]=df["Salary"].replace("Arun","65000")
df

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech    65000  12-11-2020
2  Mathiew  28.0    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6     Arun  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech    65000  12-11-2020

In [17]:
df['Salary']= df['Salary'].astype('int')
df

      Name   Age Department  Salary   Join_Date
0   Rajesh  29.0        Ops   60000  21-05-2023
1    Nasir  31.0    IT Tech   65000  12-11-2020
2  Mathiew  28.0    Support   58000  15-01-2025
3  Gilbert  29.0        Ops   60000  21-05-2021
4    Kevin  28.0    Support   61000  30-07-2024
5    Navin  35.0    Support   72000  19-08-2023
6     Arun  40.0         IT   64000  10-09-2022
7    Nasir  31.0    IT Tech   65000  12-11-2020

In [18]:
df= df.drop_duplicates()
df

      Name   Age Department  Salary   Join_Date
0   Rajesh  29.0        Ops   60000  21-05-2023
1    Nasir  31.0    IT Tech   65000  12-11-2020
2  Mathiew  28.0    Support   58000  15-01-2025
3  Gilbert  29.0        Ops   60000  21-05-2021
4    Kevin  28.0    Support   61000  30-07-2024
5    Navin  35.0    Support   72000  19-08-2023
6     Arun  40.0         IT   64000  10-09-2022

In [49]:
data = {
    "Name": ["Rajesh","Nasir","Mathiew","Gilbert","Kevin","Navin","Arun"],
    "Salary": [60000,65000, 58000,60000,61000, 72000,64000],
     "Age": [29,31,28,29,28,35,40],
    "Department": ['Ops', 'IT Tech','Support', 'Ops','Support','IT','Support'],  
}

df = pd.DataFrame(data)
app = dash.Dash(__name__)
app.layout = html.Div([
    html.H2("Employee data"),
    dash_table.DataTable(
        id='Employee data-grid',
        columns=[{"name": i, "id": i} for i in df.columns],
        data=df.to_dict('records'),
        style_table={'overflowX': 'auto'},
        style_cell={
            'textAlign': 'center',
            'padding': '10px',
            'fontFamily': 'Arial'
        },
        style_header={
            'backgroundColor': '#f2f2f2',
            'fontWeight': 'bold'
        },
       
    )
])

if __name__ == '__main__':
    app.run(debug=True)